int     addch( chtype const);
int     addchnstr( chtype const *, int);
int     addchstr( chtype const *);
int     addnstr( char const *, int);
int     addstr( char const *);
int     attroff(chtype);
int     attron(chtype);
int     attrset(chtype);
int     attr_get(attr_t *, short *, void *);
int     attr_off(attr_t, void *);
int     attr_on(attr_t, void *);
int     attr_set(attr_t, short, void *);
int     baudrate(void);
int     beep(void);
int     bkgd(chtype);
void    bkgdset(chtype);
int     border(chtype, chtype, chtype, chtype, chtype, chtype, chtype, chtype);
int     box(WINDOW *, chtype, chtype);
bool    can_change_color(void);
int     cbreak(void);
int     chgat(int, attr_t, short,  void const *);
int     clearok(WINDOW *, bool);
int     clear(void);
int     clrtobot(void);
int     clrtoeol(void);
int     color_content(short, short *, short *, short *);
int     color_set(short, void *);
int     copywin( WINDOW const *, WINDOW *, int, int, int, int, int, int, int);
int     curs_set(int);
int     def_prog_mode(void);
int     def_shell_mode(void);
int     delay_output(int);
int     delch(void);
int     deleteln(void);
void    delscreen(SCREEN *);
int     delwin(WINDOW *);
WINDOW *derwin(WINDOW *, int, int, int, int);
int     doupdate(void);
WINDOW *dupwin(WINDOW *);
int     echochar( chtype const);
int     echo(void);
int     endwin(void);
char    erasechar(void);
int     erase(void);
void    filter(void);
int     flash(void);
int     flushinp(void);
chtype  getbkgd(WINDOW *);
int     getnstr(char *, int);
int     getstr(char *);
WINDOW *getwin(FILE *);
int     halfdelay(int);
bool    has_colors(void);
bool    has_ic(void);
bool    has_il(void);
int     hline(chtype, int);
void    idcok(WINDOW *, bool);
int     idlok(WINDOW *, bool);
void    immedok(WINDOW *, bool);
int     inchnstr(chtype *, int);
int     inchstr(chtype *);
chtype  inch(void);
int     init_color(short, short, short, short);
int     init_pair(short, short, short);
WINDOW *initscr(void);
int     innstr(char *, int);
int     insch(chtype);
int     insdelln(int);
int     insertln(void);
int     insnstr( char const *, int);
int     insstr( char const *);
int     instr(char *);
int     intrflush(WINDOW *, bool);
bool    isendwin(void);
bool    is_linetouched(WINDOW *, int);
bool    is_wintouched(WINDOW *);
char   *keyname(int);
int     keypad(WINDOW *, bool);
char    killchar(void);
int     leaveok(WINDOW *, bool);
char   *longname(void);
int     meta(WINDOW *, bool);
int     move(int, int);
int     mvaddch(int, int,  chtype const);
int     mvaddchnstr(int, int,  chtype const *, int);
int     mvaddchstr(int, int,  chtype const *);
int     mvaddnstr(int, int,  char const *, int);
int     mvaddstr(int, int,  char const *);
int     mvchgat(int, int, int, attr_t, short,  void const *);
int     mvcur(int, int, int, int);
int     mvdelch(int, int);
int     mvderwin(WINDOW *, int, int);
int     mvgetch(int, int);
int     mvgetnstr(int, int, char *, int);
int     mvgetstr(int, int, char *);
int     mvhline(int, int, chtype, int);
chtype  mvinch(int, int);
int     mvinchnstr(int, int, chtype *, int);
int     mvinchstr(int, int, chtype *);
int     mvinnstr(int, int, char *, int);
int     mvinsch(int, int, chtype);
int     mvinsnstr(int, int,  char const *, int);
int     mvinsstr(int, int,  char const *);
int     mvinstr(int, int, char *);
int     mvprintw(int, int,  char const *, ...);
int     mvscanw(int, int,  char const *, ...);
int     mvvline(int, int, chtype, int);
int     mvwaddchnstr(WINDOW *, int, int,  chtype const *, int);
int     mvwaddchstr(WINDOW *, int, int,  chtype const *);
int     mvwaddch(WINDOW *, int, int,  chtype const);
int     mvwaddnstr(WINDOW *, int, int,  char const *, int);
int     mvwaddstr(WINDOW *, int, int,  char const *);
int     mvwchgat(WINDOW *, int, int, int, attr_t, short,  void const *);
int     mvwdelch(WINDOW *, int, int);
int     mvwgetch(WINDOW *, int, int);
int     mvwgetnstr(WINDOW *, int, int, char *, int);
int     mvwgetstr(WINDOW *, int, int, char *);
int     mvwhline(WINDOW *, int, int, chtype, int);
int     mvwinchnstr(WINDOW *, int, int, chtype *, int);
int     mvwinchstr(WINDOW *, int, int, chtype *);
chtype  mvwinch(WINDOW *, int, int);
int     mvwinnstr(WINDOW *, int, int, char *, int);
int     mvwinsch(WINDOW *, int, int, chtype);
int     mvwinsnstr(WINDOW *, int, int,  char const *, int);
int     mvwinsstr(WINDOW *, int, int,  char const *);
int     mvwinstr(WINDOW *, int, int, char *);
int     mvwin(WINDOW *, int, int);
int     mvwprintw(WINDOW *, int, int,  char const *, ...);
int     mvwscanw(WINDOW *, int, int,  char const *, ...);
int     mvwvline(WINDOW *, int, int, chtype, int);
int     napms(int);
WINDOW *newpad(int, int);
SCREEN *newterm( char const *, FILE *, FILE *);
WINDOW *newwin(int, int, int, int);
int     nl(void);
int     nocbreak(void);
int     nodelay(WINDOW *, bool);
int     noecho(void);
int     nonl(void);
void    noqiflush(void);
int     noraw(void);
int     notimeout(WINDOW *, bool);
int     overlay( WINDOW const *, WINDOW *);
int     overwrite( WINDOW const *, WINDOW *);
int     pair_content(short, short *, short *);
int     pechochar(WINDOW *, chtype);
int     pnoutrefresh(WINDOW *, int, int, int, int, int, int);
int     prefresh(WINDOW *, int, int, int, int, int, int);
int     printw( char const *, ...);
int     putwin(WINDOW *, FILE *);
void    qiflush(void);
int     raw(void);
int     redrawwin(WINDOW *);
int     refresh(void);
int     reset_prog_mode(void);
int     reset_shell_mode(void);
int     resetty(void);
// int     ripoffline(int, int (*)(WINDOW *, int));
int     savetty(void);
int     scanw( char const *, ...);
int     scr_dump( char const *);
int     scr_init( char const *);
int     scr_restore( char const *);
int     scr_set( char const *);
int     scrl(int);
int     scroll(WINDOW *);
int     scrollok(WINDOW *, bool);
SCREEN *set_term(SCREEN *);
int     setscrreg(int, int);
int     slk_attroff( chtype const);
int     slk_attr_off( attr_t const, void *);
int     slk_attron( chtype const);
int     slk_attr_on( attr_t const, void *);
int     slk_attrset( chtype const);
int     slk_attr_set( attr_t const, short, void *);
int     slk_clear(void);
int     slk_color(short);
int     slk_init(int);
char   *slk_label(int);
int     slk_noutrefresh(void);
int     slk_refresh(void);
int     slk_restore(void);
int     slk_set(int,  char const *, int);
int     slk_touch(void);
int     standend(void);
int     standout(void);
int     start_color(void);
WINDOW *subpad(WINDOW *, int, int, int, int);
WINDOW *subwin(WINDOW *, int, int, int, int);
int     syncok(WINDOW *, bool);
chtype  termattrs(void);
attr_t  term_attrs(void);
char   *termname(void);
void    timeout(int);
int     touchline(WINDOW *, int, int);
int     touchwin(WINDOW *);
int     typeahead(int);
int     untouchwin(WINDOW *);
void    use_env(bool);
int     vidattr(chtype);
int     vid_attr(attr_t, short, void *);
// int     vidputs(chtype, int (*)(int));
// int     vid_puts(attr_t, short, void *, int (*)(int));
int     vline(chtype, int);
int     vw_printw(WINDOW *,  char const *, va_list);
int     vwprintw(WINDOW *,  char const *, va_list);
int     vw_scanw(WINDOW *,  char const *, va_list);
int     vwscanw(WINDOW *,  char const *, va_list);
int     waddchnstr(WINDOW *,  chtype const *, int);
int     waddchstr(WINDOW *,  chtype const *);
int     waddch(WINDOW *,  chtype const);
int     waddnstr(WINDOW *,  char const *, int);
int     waddstr(WINDOW *,  char const *);
int     wattroff(WINDOW *, chtype);
int     wattron(WINDOW *, chtype);
int     wattrset(WINDOW *, chtype);
int     wattr_get(WINDOW *, attr_t *, short *, void *);
int     wattr_off(WINDOW *, attr_t, void *);
int     wattr_on(WINDOW *, attr_t, void *);
int     wattr_set(WINDOW *, attr_t, short, void *);
void    wbkgdset(WINDOW *, chtype);
int     wbkgd(WINDOW *, chtype);
int     wborder(WINDOW *, chtype, chtype, chtype, chtype, chtype, chtype, chtype, chtype);
int     wchgat(WINDOW *, int, attr_t, short,  void const *);
int     wclear(WINDOW *);
int     wclrtobot(WINDOW *);
int     wclrtoeol(WINDOW *);
int     wcolor_set(WINDOW *, short, void *);
void    wcursyncup(WINDOW *);
int     wdelch(WINDOW *);
int     wdeleteln(WINDOW *);
int     wechochar(WINDOW *,  chtype const);
int     werase(WINDOW *);
int     wgetch(WINDOW *);
int     wgetnstr(WINDOW *, char *, int);
int     wgetstr(WINDOW *, char *);
int     whline(WINDOW *, chtype, int);
int     winchnstr(WINDOW *, chtype *, int);
int     winchstr(WINDOW *, chtype *);
chtype  winch(WINDOW *);
int     winnstr(WINDOW *, char *, int);
int     winsch(WINDOW *, chtype);
int     winsdelln(WINDOW *, int);
int     winsertln(WINDOW *);
int     winsnstr(WINDOW *,  char const *, int);
int     winsstr(WINDOW *,  char const *);
int     winstr(WINDOW *, char *);
int     wmove(WINDOW *, int, int);
int     wnoutrefresh(WINDOW *);
int     wprintw(WINDOW *,  char const *, ...);
int     wredrawln(WINDOW *, int, int);
int     wrefresh(WINDOW *);
int     wscanw(WINDOW *,  char const *, ...);
int     wscrl(WINDOW *, int);
int     wsetscrreg(WINDOW *, int, int);
int     wstandend(WINDOW *);
int     wstandout(WINDOW *);
void    wsyncdown(WINDOW *);
void    wsyncup(WINDOW *);
void    wtimeout(WINDOW *, int);
int     wtouchln(WINDOW *, int, int, int);
int     wvline(WINDOW *, chtype, int);
int     addnwstr( wchar_t const *, int);
int     addwstr( wchar_t const *);
int     add_wch( cchar_t const *);
int     add_wchnstr( cchar_t const *, int);
int     add_wchstr( cchar_t const *);
int     bkgrnd( cchar_t const *);
void    bkgrndset( cchar_t const *);
int     border_set( cchar_t const *,  cchar_t const *,  cchar_t const *,  cchar_t const *,  cchar_t const *,  cchar_t const *,  cchar_t const *,  cchar_t const *);
int     box_set(WINDOW *,  cchar_t const *,  cchar_t const *);
int     echo_wchar( cchar_t const *);
int     erasewchar(wchar_t *);
int     getbkgrnd(cchar_t *);
int     getcchar( cchar_t const *, wchar_t *, attr_t *, short *, void *);
int     getn_wstr(wint_t *, int);
int     get_wch(wint_t *);
int     get_wstr(wint_t *);
int     hline_set( cchar_t const *, int);
int     innwstr(wchar_t *, int);
int     ins_nwstr( wchar_t const *, int);
int     ins_wch( cchar_t const *);
int     ins_wstr( wchar_t const *);
int     inwstr(wchar_t *);
int     in_wch(cchar_t *);
int     in_wchnstr(cchar_t *, int);
int     in_wchstr(cchar_t *);
char   *key_name(wchar_t);
int     killwchar(wchar_t *);
int     mvaddnwstr(int, int,  wchar_t const *, int);
int     mvaddwstr(int, int,  wchar_t const *);
int     mvadd_wch(int, int,  cchar_t const *);
int     mvadd_wchnstr(int, int,  cchar_t const *, int);
int     mvadd_wchstr(int, int,  cchar_t const *);
int     mvgetn_wstr(int, int, wint_t *, int);
int     mvget_wch(int, int, wint_t *);
int     mvget_wstr(int, int, wint_t *);
int     mvhline_set(int, int,  cchar_t const *, int);
int     mvinnwstr(int, int, wchar_t *, int);
int     mvins_nwstr(int, int,  wchar_t const *, int);
int     mvins_wch(int, int,  cchar_t const *);
int     mvins_wstr(int, int,  wchar_t const *);
int     mvinwstr(int, int, wchar_t *);
int     mvin_wch(int, int, cchar_t *);
int     mvin_wchnstr(int, int, cchar_t *, int);
int     mvin_wchstr(int, int, cchar_t *);
int     mvvline_set(int, int,  cchar_t const *, int);
int     mvwaddnwstr(WINDOW *, int, int,  wchar_t const *, int);
int     mvwaddwstr(WINDOW *, int, int,  wchar_t const *);
int     mvwadd_wch(WINDOW *, int, int,  cchar_t const *);
int     mvwadd_wchnstr(WINDOW *, int, int,  cchar_t const *, int);
int     mvwadd_wchstr(WINDOW *, int, int,  cchar_t const *);
int     mvwgetn_wstr(WINDOW *, int, int, wint_t *, int);
int     mvwget_wch(WINDOW *, int, int, wint_t *);
int     mvwget_wstr(WINDOW *, int, int, wint_t *);
int     mvwhline_set(WINDOW *, int, int,  cchar_t const *, int);
int     mvwinnwstr(WINDOW *, int, int, wchar_t *, int);
int     mvwins_nwstr(WINDOW *, int, int,  wchar_t const *, int);
int     mvwins_wch(WINDOW *, int, int,  cchar_t const *);
int     mvwins_wstr(WINDOW *, int, int,  wchar_t const *);
int     mvwin_wch(WINDOW *, int, int, cchar_t *);
int     mvwin_wchnstr(WINDOW *, int, int, cchar_t *, int);
int     mvwin_wchstr(WINDOW *, int, int, cchar_t *);
int     mvwinwstr(WINDOW *, int, int, wchar_t *);
int     mvwvline_set(WINDOW *, int, int,  cchar_t const *, int);
int     pecho_wchar(WINDOW *,  cchar_t const*);
int     setcchar(cchar_t*,  wchar_t const*,  attr_t const, short,  void const*);
int     slk_wset(int,  wchar_t const *, int);
int     unget_wch( wchar_t const);
int     vline_set( cchar_t const *, int);
int     waddnwstr(WINDOW *,  wchar_t const *, int);
int     waddwstr(WINDOW *,  wchar_t const *);
int     wadd_wch(WINDOW *,  cchar_t const *);
int     wadd_wchnstr(WINDOW *,  cchar_t const *, int);
int     wadd_wchstr(WINDOW *,  cchar_t const *);
int     wbkgrnd(WINDOW *,  cchar_t const *);
void    wbkgrndset(WINDOW *,  cchar_t const *);
int     wborder_set(WINDOW *,  cchar_t const *,  cchar_t const *,  cchar_t const *,  cchar_t const *,  cchar_t const *,  cchar_t const *,  cchar_t const *,  cchar_t const *);
int     wecho_wchar(WINDOW *,  cchar_t const *);
int     wgetbkgrnd(WINDOW *, cchar_t *);
int     wgetn_wstr(WINDOW *, wint_t *, int);
int     wget_wch(WINDOW *, wint_t *);
int     wget_wstr(WINDOW *, wint_t *);
int     whline_set(WINDOW *,  cchar_t const *, int);
int     winnwstr(WINDOW *, wchar_t *, int);
int     wins_nwstr(WINDOW *,  wchar_t const *, int);
int     wins_wch(WINDOW *,  cchar_t const *);
int     wins_wstr(WINDOW *,  wchar_t const *);
int     winwstr(WINDOW *, wchar_t *);
int     win_wch(WINDOW *, cchar_t *);
int     win_wchnstr(WINDOW *, cchar_t *, int);
int     win_wchstr(WINDOW *, cchar_t *);
wchar_t *wunctrl(cchar_t *);
int     wvline_set(WINDOW *,  cchar_t const *, int);
chtype  getattrs(WINDOW *);
int     getbegx(WINDOW *);
int     getbegy(WINDOW *);
int     getmaxx(WINDOW *);
int     getmaxy(WINDOW *);
int     getparx(WINDOW *);
int     getpary(WINDOW *);
int     getcurx(WINDOW *);
int     getcury(WINDOW *);
void    traceoff(void);
void    traceon(void);
char   *unctrl(chtype);
int     crmode(void);
int     nocrmode(void);
int     draino(int);
int     resetterm(void);
int     fixterm(void);
int     saveterm(void);
void    setsyx(int, int);
int     mouse_set(mmask_t);
int     mouse_on(mmask_t);
int     mouse_off(mmask_t);
int     request_mouse_pos(void);
void    wmouse_position(WINDOW *, int *, int *);
mmask_t getmouse(void);
int     alloc_pair(int, int);
int     assume_default_colors(int, int);
 char const *curses_version(void);
int     find_pair(int, int);
int     free_pair(int);
bool    has_key(int);
bool    is_cleared( WINDOW const *);
bool    is_idcok( WINDOW const *);
bool    is_idlok( WINDOW const *);
bool    is_immedok( WINDOW const *);
bool    is_keypad( WINDOW const *);
bool    is_leaveok( WINDOW const *);
bool    is_nodelay( WINDOW const *);
bool    is_notimeout( WINDOW const *);
bool    is_pad( WINDOW const *);
bool    is_scrollok( WINDOW const *);
bool    is_subwin( WINDOW const *);
bool    is_syncok( WINDOW const *);
int     set_tabsize(int);
int     use_default_colors(void);
int     wgetdelay( WINDOW const *);
WINDOW *wgetparent( WINDOW const *);
int     wgetscrreg( WINDOW const *, int *, int *);
int     wresize(WINDOW *, int, int);
bool    has_mouse(void);
int     mouseinterval(int);
mmask_t mousemask(mmask_t, mmask_t *);
bool    mouse_trafo(int *, int *, bool);
int     nc_getmouse(MEVENT *);
int     ungetmouse(MEVENT *);
bool    wenclose( WINDOW const *, int, int);
bool    wmouse_trafo( WINDOW const *, int *, int *, bool);
int     addrawch(chtype);
int     insrawch(chtype);
bool    is_termresized(void);
int     mvaddrawch(int, int, chtype);
int     mvdeleteln(int, int);
int     mvinsertln(int, int);
int     mvinsrawch(int, int, chtype);
int     mvwaddrawch(WINDOW *, int, int, chtype);
int     mvwdeleteln(WINDOW *, int, int);
int     mvwinsertln(WINDOW *, int, int);
int     mvwinsrawch(WINDOW *, int, int, chtype);
int     raw_output(bool);
int     resize_term(int, int);
WINDOW *resize_window(WINDOW *, int, int);
int     waddrawch(WINDOW *, chtype);
int     winsrawch(WINDOW *, chtype);
char    wordchar(void);
wchar_t *slk_wlabel(int);
void    PDC_debug( char const *, ...);
void    PDC_get_version(PDC_VERSION *);
int     PDC_ungetch(int);
int     PDC_set_blink(bool);
int     PDC_set_bold(bool);
int     PDC_set_line_color(short);
void    PDC_set_title( char const *);
int     PDC_clearclipboard(void);
int     PDC_freeclipboard(char *);
int     PDC_getclipboard(char **, long *);
int     PDC_setclipboard( char const *, long);
unsigned long PDC_get_key_modifiers(void);
int     PDC_return_key_modifiers(bool);
WINDOW *Xinitscr(int, char **);
void    XCursesExit(void);
int     sb_init(void);
int     sb_set_horz(int, int, int);
int     sb_set_vert(int, int, int);
int     sb_get_horz(int *, int *, int *);
int     sb_get_vert(int *, int *, int *);
int     sb_refresh(void);
int     touchoverlap( WINDOW const *, WINDOW *);
int     underend(void);
int     underscore(void);
int     wunderend(WINDOW *);
int     wunderscore(WINDOW *);
